name: Deploy DocFX _site to GitHub Pages

on:
  push:
    branches:
      - main  # your source branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy _site to GitHub Pages
        uses: peaceiris/actions-gh-pages@v7
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # THIS IS REQUIRED
          publish_dir: ./_site
          keep_files: true